# This file sets the configuration options related to the backend design.
# If your backend is simple, you probably can rely on the default values of
# the options and just define the value of the 'site_name' option.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    site_name: 'easy-admin-skeleton'
    design:
        brand_color: '#2980b9'
        form_theme:   'vertical'
        color_scheme: 'dark'
        assets:
            favicon: '/favicon.ico'
            css:
                - '/bundles/app/stylesheets/demo.css'
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i:s'
    list:
        max_results: 30
    show:
        max_results: 20
