easy_admin:
    site_name: 'easy-admin-skeleton'
    design:
        brand_color: '#2980b9'
        assets:
            favicon: '/favicon.ico'
    formats:
        date:     'd.m.Y'
        time:     'H:i'
        datetime: 'd.m.Y H:i:s'
    list:
        max_results: 30
    show:
        max_results: 20
    entities:
        Category:
            class: AppBundle\Entity\Category
        Product:
            class: AppBundle\Entity\Product
            image_base_path: '/uploads/images/products'
            list:
                fields:
                    - 'name'
                    - 'ean'
                    - { property: 'image', type: 'image' }
                    - 'price'
                    - 'enabled'
        CheapProduct:
            class: AppBundle\Entity\Product
            list:
                dql_filter: 'entity.price < 10.00'
        Purchase:
            class: AppBundle\Entity\Purchase
        PurchaseItem:
            class: AppBundle\Entity\PurchaseItem
